import React, { useMemo, useReducer, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { db } from '../firebase'
import { useList } from 'react-firebase-hooks/database'
import { ref, get, set } from 'firebase/database'

const Home: NextPage = () => {
  const [snapshots, loading, error] = useList(ref(db, 'users'))
  const [{ firstName, lastName }, setState] = useReducer(
    (prevState: any, newState: any) => ({
      ...prevState,
      ...newState,
    }),
    {
      firstName: '',
      lastName: '',
    }
  )

  const users = useMemo(
    () => snapshots?.map((snap) => snap.val()) || [],
    [snapshots]
  )

  const create = async () => {
    await set(ref(db, 'users'), [
      ...users,
      {
        firstName,
        lastName,
      },
    ])

    setState({ firstName: '', lastName: '' })
  }

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target

    setState({ [name]: value })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Registration</h1>
        <div
          style={{
            marginTop: 10,
          }}
        >
          <input
            type="text"
            name="firstName"
            value={firstName}
            placeholder="First Name"
            onChange={handleChange}
          />
          <input
            type="text"
            name="lastName"
            value={lastName}
            placeholder="Last Name"
            onChange={handleChange}
          />
          <button onClick={create}>add user </button>
          <ul>
            {users.map((user) => {
              return (
                <li key={user.firstName + user.lastName}>
                  {user.firstName} {user.lastName}
                </li>
              )
            })}
          </ul>
        </div>
      </main>
    </div>
  )
}

export default Home
